dubbo:
  application:
    name: manage-service-provider
  registry:
    protocol: zookeeper
  protocol:
    name: dubbo
  monitor:
    protocol: registry

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    username: "hidden"
  #    password: "hidden"
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
#    host: "hidden"